config/routes.rb
ProjectCurrently::Application.routes.draw do
  
  root 'users#new'

  resources :comments
  resources :support_requests

  resources :projects
  
  get '/user/:user_id' => 'user#show'
  get '/dashboard' => 'projects#dashboard'

  resources :users
  resources :sessions, only: [:create, :new, :destroy]

  get "signup" => "users#new", :as => "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to:"sessions#create"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/comment.rb
class Comment

  include Mongoid::Document


  belongs_to :user
  belongs_to :project

  field :content, type: String
end

app/models/project.rb
class Project
  
  include Mongoid::Document
  include Mongoid::Paperclip


  has_many :comments
  belongs_to :user

  field :name, type: String
  field :description, type: String
  
  has_mongoid_attached_file :photo, :styles => { :small => "150x150>" },  
  :url => "/assets/products/:id/:style/:basename.:extension",  
  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension" 

end

app/models/user.rb
class User

  include Mongoid::Document


  has_many :comments
  has_many :projects
  #has_many :supportrequests

  field :name, type: String
  field :email, type: String
  field :school, type: String
  field :role, type: String, default: "user"

  validates :role, :inclusion => { :in => ["user", "admin"] }

  validates :email, :presence => { :message => "Cannot have account without email"}
  validate :is_in_right_school

  def is_in_right_school
    if :school.nil?
  	errors.add(:school, "Must have school field")
    elsif( not school.to_s.eql? "Columbia University" and not school.to_s.eql? "Yale University" and not school.to_s.eql? "Brown University" )
      errors.add(:school, "Must be in Columbia University, Yale University, or Brown University, you entered: " + school.to_s)
    end
  end

  validates :name, :presence => { :message => "Must have a name"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_user

  def current_user
    if @current_user.nil?
      @current_user = User.find(session[:user_id]) if session[:user_id]
    end
  end
  helper_method :current_user
  
  def require_user
    if current_user
      return true
    end
    redirect_to root_url, alert: "Not a valid user"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
  #def index
  #  @comments = Comment.all
  #end
  
  def show
  end

  def new
    @comment = Comment.new
    @form_action = project_path(@project)
    @new = true
  end
 
  def edit
    @form_action = project_path(@project, @comment)
    @new = false
  end
  
  def create
    @project = Project.find(params[:comment][:project_id])
    @comment = @project.comments.new({:content => params[:comment][:content]})
    if @comment.save
      redirect_to @project, notice: "Comment created."
    else
      redirect_to @project, notice: "Comment not created."
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_user, only: [:embed, :index, :show]

  def index
    current_user
    @projects = Project.all
  end
  
  def dashboard
    @projects = Project.where(user_id: session[:user_id])
  end

  def show
    current_user
    @project = Project.find(params[:id])
    @comment = @project.comments.build
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]
    @project.comments = nil

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :owner, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	skip_before_filter :require_user, :only => [:new, :create]
	
	def new
	end
	
	def create
		user = nil
		begin
			user = User.find_by(email: params[:session][:email])
		rescue Exception
		end
			
		if user
			session[:user_id] = user.id
			redirect_to '/dashboard'
		else
			redirect_to root_url, :flash => { :error => "Username was not found" }
		end  
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  skip_before_action :is_admin, only: [:new, :create]

  def index
    if @current_user[:role] == "admin"
      @users = User.all
    elsif @current_user
      redirect_to @current_user
    else
      redirect_to root_url
    end
  end

  def show
    @user = @current_user
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    params[:user][:email].downcase!
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    redirect_to root_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :school)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <%= f.hidden_field :project_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <% if @current_user %>
      Logged in as: <%= @current_user.name %>
    <% end %>
    <br />
    David Watkins • Copyright &copy;<%= Time.new.year %> <%= yield :footer %>
  </div>
</footer>
<script src=<%= asset_path 'bootstrap.js' %>></script>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Project Currently</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/projects">Projects</a></li>
        <% if not @current_user.nil? %>
          <li class="active"><a href="/dashboard">Dashboard</a></li>
	  <li class="active"><%= link_to "Logout", "/logout" %></li>
	<% else %>
	  <li class="active"><%= link_to "Login", '/login' %></li>
	  <li class="active"><%= link_to "Sign up", 'users#new' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectCurrently</title>
 
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application.css", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render :partial => "layouts/nav" %>

	<div class="container">
	  <%= yield %>
	</div>

	<%= render :partial => "layouts/footer" %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:multipart => true} do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :picture %><br>
      <%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/dashboard.html.erb
<h2>My Projects</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>        </th>
      <th>        </th>
      <th>        </th>
      <th>        </th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %>  </td>
        <td><%= project.description %>   </td>
        <td><%= link_to 'View', project %>   </td>
        <% if @current_user and (@current_user.role.eql? "admin" or project.user_id == @current_user.id) %>
          <td><%= link_to 'Edit', edit_project_path(project) %>  </td>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>  </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to 'New Project', new_project_path %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name|</th>
      <th>Description|</th>
      <th>        </th>
      <th>        </th>
      <th>        </th>
      <th>        </th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %>  </td>
        <td><%= project.description %>   </td>
        <td><%= link_to 'View', project %>   </td>
        <% if @current_user and (@current_user.role.eql? "admin" or project.user_id == @current_user.id) %>
          <td><%= link_to 'Edit', edit_project_path(project) %>  </td>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>  </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @current_user and (@current_user.role.eql? "admin" or project.user_id == @current_user.id) %>
  <%= link_to 'New Project', new_project_path %>
<% else %>
  <%= link_to 'Sign up to create a project', '/signup' %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= User.find(@project.user_id).name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @project.photo.url %>
</p>

<h3>Comments</h3>  

<ul id="comments" class="formList">  
  <% @project.comments.each do |comment| %>
    <% if comment.content and !(comment.content.eql? "") %>
      <li><div class="commentBox"><%= comment.content %></div></li>
    <% end %>
  <% end %>  
</ul>

<% if @current_user %>
  <h5>New Comment</h5>  
  <%= form_for @comment do |f| %> 
    <ol class="formList">  
      <li>  
        <br />
        <%= f.text_area :content, :rows => 5 %>
        <%= f.hidden_field :project_id %>
      </li>  
      <li><%= f.submit "Add comment" %></li>  
    </ol>  
  <% end %>
<% end %>
  
<% if @current_user and (@current_user.role.eql? "admin" or @project.user_id == @current_user.id) %>

  <%= link_to 'Edit', edit_project_path(@project) %>

<% end %>

app/views/users/_form.html.erb
<% if @user %>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :school %><br>
      <%= f.text_field :school %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>School</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody class="rowPadded">
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.school %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>